# Week 1 Project: AI for Landslide Susceptibility in Himalayan & Western Ghats
### Climate Risk and Disaster Management

This project explores a dataset related to landslide susceptibility mapping in the Himalayan & Western Ghats regions.

In [1]:
# 1. Import necessary libraries
import pandas as pd
import numpy as np

In [2]:
# 2. Load the dataset
file_path = 'landslide_dataset.csv'  # Ensure this file is in the same directory as the notebook
df = pd.read_csv(file_path)
df.head()

,Rainfall_mm,Slope_Angle,Soil_Saturation,Vegetation_Cover,Earthquake_Activity,Proximity_to_Water,Landslide,Soil_Type_Gravel,Soil_Type_Sand,Soil_Type_Silt
0,206.181018,58.275001,0.892798,0.339463,4.390047,0.099975,1,0,0,0
1,218.887334,36.679801,0.657147,0.360355,4.141029,0.832443,1,0,0,1
2,181.850867,31.363874,0.673362,0.221697,5.311891,0.023062,1,0,0,1
3,228.716199,38.995134,0.618666,0.489502,4.581928,0.785176,1,0,0,1
4,179.951067,42.998205,0.836966,0.118580,5.518862,0.450499,1,0,0,0

In [3]:
# 3. Explore the dataset

# Basic info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Rainfall_mm          2000 non-null   float64
 1   Slope_Angle          2000 non-null   float64
 2   Soil_Saturation      2000 non-null   float64
 3   Vegetation_Cover     2000 non-null   float64
 4   Earthquake_Activity  2000 non-null   float64
 5   Proximity_to_Water   2000 non-null   float64
 6   Landslide            2000 non-null   int64
 7   Soil_Type_Gravel     2000 non-null   int64
 8   Soil_Type_Sand       2000 non-null   int64
 9   Soil_Type_Silt       2000 non-null   int64
dtypes: float64(6), int64(4)
memory usage: 156.4 KB

In [4]:
# Summary statistics
df.describe()

,Rainfall_mm,Slope_Angle,Soil_Saturation,Vegetation_Cover,Earthquake_Activity,Proximity_to_Water,Landslide,Soil_Type_Gravel,Soil_Type_Sand,Soil_Type_Silt
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000,2000.0000,2000.00000
mean,176.688462,29.985404,0.540316,0.522862,3.604771,1.001867,0.500000,0.25850,0.2415,0.26100
std,65.724685,15.175902,0.295665,0.260426,1.895955,0.579964,0.500125,0.43792,0.4281,0.43929
min,50.036151,5.003944,0.000652,0.100005,0.001641,0.000653,0.000000,0.00000,0.0000,0.00000
25%,128.379762,18.018061,0.265634,0.295475,1.973415,0.500808,0.000000,0.00000,0.0000,0.00000
50%,177.013772,27.772833,0.599887,0.500191,3.996429,0.999761,0.500000,0.00000,0.0000,0.00000
75%,228.742286,41.683190,0.801994,0.740690,5.233897,1.505294,1.000000,1.00000,0.0000,1.00000
max,299.919102,59.966732,0.998831,0.999837,6.498670,1.999636,1.000000,1.00000,1.0000,1.00000

In [5]:
# Check for missing values
df.isnull().sum()

Rainfall_mm            0
Slope_Angle            0
Soil_Saturation        0
Vegetation_Cover       0
Earthquake_Activity    0
Proximity_to_Water     0
Landslide              0
Soil_Type_Gravel       0
Soil_Type_Sand         0
Soil_Type_Silt         0
dtype: int64